export PATH="$HOME/.local/bin:$BOB_NVIM_HOME:$CARGO_HOME/bin:$VOLTA_HOME/bin:$GOPATH/bin:$PATH"
export FPATH="$HOME/.config/zsh/completions:$HOME/.local/share/sheldon:$FPATH"
export CARGO_HOME="$HOME/.cargo"
export BOB_NVIM_HOME="$HOME/.local/share/bob/nvim-bin"
export VOLTA_HOME="$HOME/.volta"
export GOPATH="$HOME/Developer/go"
export GOROOT=
export EDITOR="nvim"
export DISPLAY=:0
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export TERM="alacritty"
export VIMRC="$HOME/.config/nvim/min.lua"
export VIMINIT="source $VIMRC"
export LESSOPEN='|~/.lessfilter %s'
