set runtimepath+=~/.config/vim
set termguicolors

syntax on

call plug#begin()
Plug 'ghifarit53/tokyonight-vim'
call plug#end()

let g:tokyonight_style = 'night' " available: night, storm

colorscheme tokyonight

