# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"
PATH = 'export PATH="{{ dir }}:$PATH"'
path = 'path=( "{{ dir }}" $path )'
fpath = 'fpath=( "{{ dir }}" $fpath )'
fpath-src = 'fpath=( "{{ dir }}/src" $fpath )'

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fzf-tab-source]
github = "Freed-Wu/fzf-tab-source"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"
apply = ["defer"]

[plugins.macos]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/macos/macos.plugin.zsh"
apply = ["defer"]

[plugins.web-search]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/web-search/web-search.plugin.zsh"
apply = ["defer"]

[plugins.vscode]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/vscode/vscode.plugin.zsh"
apply = ["defer"]

[plugins.git]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/git/git.plugin.zsh"
apply = ["defer"]

[plugins.git-core]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/lib/git.zsh"
apply = ["defer"]

[plugins.functions]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/lib/functions.zsh"
apply = ["defer"]

[plugins.rust]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/rust/rust.plugin.zsh"
apply = ["defer"]

[plugins.golang]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/golang/golang.plugin.zsh"
apply = ["defer"]

[plugins.tmux-only]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/tmux/tmux.only.conf"
apply = ["defer"]

[plugins.tmux-extra]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/tmux/tmux.extra.conf"
apply = ["defer"]

[plugins.tmux]
remote = "https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/tmux/tmux.plugin.zsh"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer", "fpath-src"]

[plugins.nix-zsh-completions]
github = "nix-community/nix-zsh-completions"
apply = ["defer", "fpath"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]
