# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌─╼\[](bg: #445566)$time[\]](bg: #445566)$cmd_duration
[└─╼\[](bg: #445566)$directory[\]](bg: #445566)$git_branch$git_status$git_state$git_commit
$character'''

# Inserts a blank line between shell prompts
add_newline = true

# Extend command timeouts
command_timeout = 30000 # 30 seconds

[character]
success_symbol = "[▶](bg: green)"
error_symbol = "[▶](bg: #BB6666)"

[time]
time_format = "%H:%M"
format = '[$time](fg:#77AACC)'
disabled = false

[directory]
format = '[$path](fg:#77AACC)'
disabled = false

[git_branch]
format = '''

[ ╰╼\[](bg: #445566)[$branch](bg: green)'''
disabled = false

[git_status]
format = '([$all_status$ahead_behind](fg: #DDDDEE))'
conflicted = " *"
ahead = " ⇡"
behind = " ⇣"
diverged = " ⇕"
up_to_date = " ="
untracked = " ?"
stashed = " #"
modified = " !"
staged = " +"
renamed = " »"
deleted = " x"
disabled = false

[git_state]
format = '([$state\($progress_current/$progress_total\)](fg: #DDDDEE))'
rebase = " REBASING"
merge = " MERGING"
revert = " REVERTING"
cherry_pick = " CHERRY-PICKING"
bisect = " BISECTING"
am = " AM"
am_or_rebase = " AM/REBASE"
disabled = false

[git_commit]
format = '[\]](bg: #445566)[╾─╼\[](bg: #445566)[$hash](fg:#77CCDD)[\]](bg: #445566)'
commit_hash_length = 7
only_detached = false
tag_disabled = true
disabled = false

[cmd_duration]
format = '[╾─╼\[](#445566)[DURATION $duration](fg: #BB6666)[\]](#445566)'
disabled = false

# disabled
[aws]
disabled = true
[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[spack]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
