# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌─╼\[](fg:#383E5A)$time[\]](fg:#383E5A)$cmd_duration
[└─╼\[](fg:#383E5A)$directory[\]](fg:#383E5A)$container$docker_context$golang$lua$deno$nodejs$rust$shell$git_branch$git_status$git_state$git_commit
$status$character'''

# Inserts a blank line between shell prompts
add_newline = true

# Extend command timeouts
command_timeout = 30000 # 30 seconds

[character]
success_symbol = "[▶](fg:#9ECE6A)"
error_symbol = "[▶](fg:#F93357)"

[status]
format = '[$status]($style) '
disabled = false

[time]
time_format = "%-I:%M %p"
format = '[$time](fg:#7AA2F7)'
disabled = false

[directory]
format = '[$path](fg:#7AA2F7)'
disabled = false

[git_branch]
format = '''

[ ╰╼\[](fg:#383E5A)[$branch](fg:#9ECE6A)'''
disabled = false

[git_status]
format = '([$all_status$ahead_behind](fg:#C0CAF5))'
conflicted = " *"
ahead = " ⇡"
behind = " ⇣"
diverged = " ⇕"
up_to_date = " ="
untracked = " ?"
stashed = " #"
modified = " !"
staged = " +"
renamed = " »"
deleted = " x"
disabled = false

[git_state]
format = '([$state\($progress_current/$progress_total\)](fg:#C0CAF5))'
rebase = " REBASING"
merge = " MERGING"
revert = " REVERTING"
cherry_pick = " CHERRY-PICKING"
bisect = " BISECTING"
am = " AM"
am_or_rebase = " AM/REBASE"
disabled = false

[git_commit]
format = '[\]](fg:#383E5A)[╾─╼\[](fg:#383E5A)[$hash](fg:#2AC3DE)[\]](fg:#383E5A)'
commit_hash_length = 7
only_detached = false
tag_disabled = true
disabled = false

[cmd_duration]
format = '[╾─╼\[](fg:#383E5A)[DURATION $duration]()[\]](fg:#383E5A)'
disabled = false

[container]
format = '[╾─╼\[](fg:#383E5A)[$symbol($name)](fg:#0db7ed)[\]](fg:#383E5A)'

[deno]
format = '[╾─╼\[](fg:#383E5A)[$symbol($version)](fg:green bold)[\]](fg:#383E5A)'
symbol = ' '

[docker_context]
symbol = '󰡨 '
detect_folders = ["docker"]
format = '[╾─╼\[](fg:#383E5A)[$symbol($context)](fg:#0db7ed)[\]](fg:#383E5A)'

[golang]
symbol = '󰟓 '
format = '[╾─╼\[](fg:#383E5A)[$symbol($version)](fg:#00ADD8)[\]](fg:#383E5A)'

[lua]
symbol = '󰢱 '
format = '[╾─╼\[](fg:#383E5A)[$symbol($version)](fg:#0000FF)[\]](fg:#383E5A)'

[nodejs]
detect_extensions = []
detect_folders = []
format = '[╾─╼\[](fg:#383E5A)[$symbol($version)](fg:#68a063)[\]](fg:#383E5A)'

[rust]
symbol = '󱘗 '
format = '[╾─╼\[](fg:#383E5A)[$symbol($version)](fg:#CE412B)[\]](fg:#383E5A)'

# disabled
[aws]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[spack]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
